### ISSUE TITLE
还有没有更新啊？

### ISSUE THREAD

**Issue by gguava** [suxianbaozi/websocket4ie#1]
很少可以支持ie6的 真心不懂flash脚本 希望您能继续维护

这个咋回复？最近忙一直没搞这玩意，有空出个完整的demo出来

**Comment by suxianbaozi** [comment]
一直没啥时间哈，过阵子 出个demo
在 2013-9-24，下午5:16，guava tan notifications@github.com 写道：

**Comment by zijjj** [comment]
这都过了好几个一阵子了。。

**Comment by suxianbaozi** [comment]
项目没用了，现在websocket 已经全系支持了，
